name: Release SDK & UI

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - run: yarn install --immutable
      - run: yarn build

      # - name: Test SDK & UI
      #   run: yarn test

      # - name: Test SDK integration against live contracts
      #   if: ${{ github.ref == 'refs/heads/master' }}
      #   run: yarn test-live

      - name: Release SDK on NPM
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # TODO: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release

      # - name: Login to Docker Hub
      #   uses: azure/docker-login@v1
      #   if: ${{ github.event_name == 'push' }}
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # - name: Release dev-frontend on Docker Hub
      #   if: ${{ github.event_name == 'push' }}
      #   run: |
      #     docker-compose build
      #     docker-compose push
      #   working-directory: ./packages/dev-frontend
      #   env:
      #     TAG: ${{ fromJSON('{ "refs/heads/master":"latest", "refs/heads/main":"next" }')[github.ref] }}

      # Must come after build step
      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # TODO: master
        with:
          name: dapp
          path: packages/dev-frontend/dist
